### ISSUE TITLE
Idea for DgmlBuilder

### ISSUE THREAD

**Issue by sirxyzzy** [merijndejonge/DgmlBuilder#1]
I naturally model using POCO, so relationships are normally just a collection of some other type, or in the case of a 1:x a simple reference, either way, a Link normally relates two different classes, yet the built in LinkBuilder takes a single type, I therefore find my self doing the following...

                LinkBuilders = new LinkBuilder[]
                {
                    new LinkBuilder<Tuple<Project,Project>>(x => new Link
                    {
                        Source = x.Item1.Id,
                        Target = x.Item2.Id,
                        Label = "references",
                    }),
                    new LinkBuilder<Tuple<Module, Module>>(x => new Link
                    {
                        Source = x.Item1.Name,
                        Target = x.Item2.Name,
                        Label = "dependsOn",
                    }),
                    new LinkBuilder<Tuple<Module, Project>>(x => new Link
                    {
                        Source = x.Item1.Name,
                        Target = x.Item2.Id,
                        Label = "exports",
                    })
                },

I was thinking instead to create a LinkBuilder which takes TWO types, then I can do this...

                LinkBuilders = new LinkBuilder[]
                {
                    new LinkBuilder<Project,Project>((s,t) => new Link
                    {
                        Source = s.Id,
                        Target = t.Id,
                        Label = "references",
                    }),
                    new LinkBuilder<Module, Module>((s,t)=> new Link
                    {
                        Source = s.Name,
                        Target = t.Name,
                        Label = "dependsOn",
                    }),
                    new LinkBuilder<Module, Project>((s,t) => new Link
                    {
                        Source = s.Name,
                        Target = t.Id,
                        Label = "exports",
                    })
                },

If you want me to submit a pull request for this, please ask, the only hack it the base class has to take a single type, to which I provide "typeof(T)"

**Comment by sirxyzzy** [comment]
Following up on my comment, I see now how, with the current framework, this is awkward, how, for example, would Accept work amongst others, yeah, hard to implement with the current architecture, maybe though you have ideas on this. Even my Tuple based hackaround is going to be rather evil, looks like this won't work out for my use case

**Comment by merijndejonge** [comment]
Sorry for my late reply,

Did you have a look at the types visualizer example that is included in the DgmlBuilder project:
* https://github.com/merijndejonge/DgmlBuilder/tree/master/src/examples/TypesVisualizer

I think that pretty-much demonstrates what you;re looking for. It creteas a type dependency graph from a collection of POCO types.

Let me know if you need further help.
