### ISSUE TITLE
HasCategory replaced by GroupLabel

### ISSUE THREAD

**Issue by Droppers** [merijndejonge/DgmlBuilder#13]
Why are style conditions replaced by HasCategory(GroupLabel), it defeats the purpose of GroupLabel and HasCategory. In my instance the GroupLabel and Category are different, it is also possible to have multiple HasCategory's.

https://github.com/merijndejonge/DgmlBuilder/blob/75b75895ae9543a864a62876f5dcf080cddbf697/src/DgmlBuilder/DgmlBuilder.cs#L128

I think Conditions shouldn't be overwritten, also a Link can have nested Category nodes.

But other than that it's a great library though!

**Comment by merijndejonge** [comment]
Thanks for your feedback. It is a mechanism to select  styles. Feel free to propose an alternative mechanism. When I created this library, I didn't consider me as a DGML-export. So,I'm sure there is plenty room for improvement :-)
