### ISSUE TITLE
Move IGraphAnalysis.cs to Analyses folder/namespace

### ISSUE THREAD

**Issue by shaggygi** [merijndejonge/DgmlBuilder#17]
Would it be more appropriate to move this file (`IGraphAnalysis.cs`) and update namespace where other Analysis files are located?

Currently set to `OpenSoftware.DgmlTools.Model` instead of `OpenSoftware.DgmlTools.Analyses`.

This would be a breaking change.

**Comment by merijndejonge** [comment]
Yes, I'm fine with that. It's a breaking change, but easy to fix :-) Could you be so kind to create a pull request for this?

**Comment by shaggygi** [comment]
Yes, I will update this afternoon.  Thx.
