### ISSUE TITLE
Color - what's that?

### ISSUE THREAD

**Issue by LexaGV** [merijndejonge/DgmlBuilder#20]
I tried to compile lib under .NET FW 4.8, but stuck at place where you use Color class(struct?). From what assembly it is?? No any mention in a project. Just in case, it's in CategoryColorAnalysis.cs

**Comment by merijndejonge** [comment]
Color is in System.Drawing

**Comment by LexaGV** [comment]
Surprisingly, C# file doesn't import any "System.Drawing". Is it not necessary anymore?

**Comment by merijndejonge** [comment]
Good question. Not sure how that works exactly.
Can you continue now?

**Comment by LexaGV** [comment]
Yes, thank you! Compiled w/o any changes (just recreated project for FW 4.8). It's good lib for using DGML w/o MS tools.

**Comment by merijndejonge** [comment]
Ok, then I close this issue.
