### ISSUE TITLE
Strong Name Signed NuGet Package

### ISSUE THREAD

**Issue by cptjazz** [merijndejonge/DgmlBuilder#3]
Hi, could you be so kind and do a new release of the nuget package (1.13.0) with the strong named assembly changes of PR #2? 

Thanks :)

**Comment by merijndejonge** [comment]
Done. 
Sorry for the delay.
Can you check and let me know if it meets your needs?

Thanks

**Comment by cptjazz** [comment]
Works perfectly! Thanks!
