### ISSUE TITLE
Missing "Client" shape

### ISSUE THREAD

**Issue by JanKinable** [merijndejonge/DgmlBuilder#4]
The link to the shape "https://raw.githubusercontent.com/merijndejonge/Structurizr.Dgml/master/src/Structurizr.Dgml/Shapes/WebBrowser.png" is broken.

**Comment by merijndejonge** [comment]
Thanks for reporting, however, the issue belongs to the project https://github.com/merijndejonge/Structurizr.Dgml.
I'll create the issue there and close this one.
