### ISSUE TITLE
Nuget package with .NET Standard support?

### ISSUE THREAD

**Issue by smaillet** [merijndejonge/DgmlBuilder#8]
The current released NuGet package 1.13 is almost a year old and doesn't support .NET Standard. I can see from the current code that this has been resolved and the library now targets NET Standard. Can we get an official updated NuGet package? I have a library that uses this but have to bracket it with conditional compilation for net47, which we aren't even targeting anymore - moved to all up net standard with .NET5 transitioning to core.

**Comment by merijndejonge** [comment]
Thanks for asking.
I've just released the latest version targeting NET Standard as version 1.14.

https://www.nuget.org/packages/OpenSoftware.DgmlBuilder/1.14.0

Please let me know if you encounter any issues
